apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nlm58kp3e-go 
  janus-idp.io/tekton: nlm58kp3e-go
  backstage.io/kubernetes-id: nlm58kp3e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nlm58kp3e-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml