apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nlm58kp3e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nlm58kp3e-go 
  name: nlm58kp3e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nlm58kp3e-go 
